### PR TITLE
Fixes #49

### LINKED ISSUE #49: ResourceCleanerScheduler invokes acceptOffers incorrectly
`ResourceCleanerScheduler` invokes `driver.acceptOffers` with recommendations from multiple agents in a single call.

### PR DESCRIPTION
**Pull request by mohitsoni**
This PR ensures that `ResourceCleanerScheduler` invokes one `accept` call for Operation(s) related to each agent.

### CODE REVIEW

File: src/main/java/org/apache/mesos/offer/ResourceCleanerScheduler.java [hunk 1]
```diff
@@ -17,13 +18,39 @@
...
-
     this.resourceCleaner = resourceCleaner;
     this.offerAccepter = offerAccepter;
   }
 
   public List<OfferID> resourceOffers(SchedulerDriver driver, List<Offer> offers) {
-    List<OfferRecommendation> recommendations = resourceCleaner.evaluate(offers);
-    return offerAccepter.accept(driver, recommendations);
+    final List<OfferRecommendation> recommendations = resourceCleaner.evaluate(offers);
+    final Map<Protos.SlaveID, List<OfferRecommendation>> recommendationsGroupedByAgents =
```
Comment (nickbp) [inline src/main/java/org/apache/mesos/offer/ResourceCleanerScheduler.java]: Add an explanation for why these need to be grouped before passing to the OfferAccepter? does this affect the accept logic?

File: src/main/java/org/apache/mesos/offer/ResourceCleanerScheduler.java [hunk 2]
```diff
@@ -17,13 +18,39 @@
...
+
+    final List<OfferID> processedOffers = new ArrayList<>(offers.size());
+    for (Map.Entry<Protos.SlaveID, List<OfferRecommendation>> entry : recommendationsGroupedByAgents.entrySet()) {
+      processedOffers.addAll(offerAccepter.accept(driver, recommendationsGroupedByAgents.get(entry.getKey())));
+    }
+
+    return processedOffers;
+  }
+
+  protected Map<Protos.SlaveID, List<OfferRecommendation>> groupRecommendationsByAgent(
```
Comment (nickbp) [inline src/main/java/org/apache/mesos/offer/ResourceCleanerScheduler.java]: Couldn't hurt to add a note that this is intentionally visible for testing

**Comment by nickbp** [comment]
Just nitpicks about adding comments, LGTM otherwise
